apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-container
        image: 10.152.183.123:5000/scrapingtest-web-service:latest
        ports:
        - containerPort: 80 # Nginx default port is 80