# Käytä virallista Nginx-kuvaa perustana
FROM docker.io/nginx:alpine

# Kopioi staattiset tiedostot Nginxin oletushakemistoon
# Alpine-versiossa se on /usr/share/nginx/html
COPY . /usr/share/nginx/html