server {
listen 80;
server_name localhost;

# Tämä lohko käsittelee kaikki saapuvat pyynnöt ja palvelee staattiset tiedostot.
location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    # Tärkeä asetus React/SPA-sovelluksille, varmistaa, että kaikki polut palauttavat index.html:n
    try_files $uri $uri/ /index.html;
}

# Muut location-lohkot (kuten /api/) poistettu, koska Kubernetes Ingress hoitaa ne.

}